services:
  postgres:
    image: postgres:16-alpine
    container_name: fitzone_postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_DB: fitzone_db
      POSTGRES_USER: fitzone_user
      POSTGRES_PASSWORD: fitzone_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitzone-net

volumes:
  postgres_data:
    driver: local

networks:
  fitzone-net:
    driver: bridge
